<#
.SYNOPSIS
    Verifies the mkdocs.yml nav matches the markdown files under docs_dir.

.DESCRIPTION
    Reads the nav section of mkdocs.yml and compares it with the *.md files
    under the configured docs_dir (Docs\ in this repo), in both directions:

    - Every nav entry must point at a file that exists, so the site never
      builds with a dead nav link.
    - Every markdown file must appear in the nav, so a page generated by
      Docs.ps1 (or added by hand) cannot be silently left off the site.

    Comparisons are case-sensitive because the published site is built on
    Linux, where a case mismatch that Windows tolerates becomes a 404.

    The nav paths are extracted with a line-based parse of the nav block
    rather than a YAML parser, so the test adds no module dependency. Only
    entries ending in .md are collected; external links are ignored.
    Integration: real repo files, nothing mocked, nothing mutated.
#>

Describe 'mkdocs.yml navigation' -Tag 'integration', 'acceptance' {

    BeforeAll {
        $RepoRootParams = @{
            Path      = $PSScriptRoot
            ChildPath = '..\..'
        }
        $script:RepoRoot = (Resolve-Path -Path (Join-Path @RepoRootParams)).Path
        $script:MkDocsPath = Join-Path -Path $script:RepoRoot -ChildPath 'mkdocs.yml'
        $MkDocsLines = @(Get-Content -Path $script:MkDocsPath)

        # docs_dir names the folder mkdocs serves. mkdocs defaults to 'docs'
        # when the key is absent.
        $script:DocsDir = 'docs'
        foreach ($Line in $MkDocsLines) {
            if ($Line -match '^docs_dir:\s*(\S+)\s*$') {
                $script:DocsDir = $Matches[1]
                break
            }
        }
        $script:DocsPath = Join-Path -Path $script:RepoRoot -ChildPath $script:DocsDir

        # Collect the .md paths in the nav block: everything between the 'nav:'
        # line and the next top-level key. An entry is '- Title: path.md' or
        # '- path.md', at any indent.
        $script:NavPaths = [System.Collections.Generic.List[string]]::new()
        $InNav = $false
        foreach ($Line in $MkDocsLines) {
            if ($Line -match '^nav:') {
                $InNav = $true
                continue
            }
            if ($InNav -and $Line -match '^\S') { $InNav = $false }
            if (-not $InNav) { continue }
            if ($Line -match '^\s*-\s+(?:[^:]+:\s*)?(\S+\.md)\s*$') {
                $script:NavPaths.Add($Matches[1])
            }
        }

        # Relative, forward-slash paths to mirror how the nav writes them.
        $script:DocFiles = [System.Collections.Generic.List[string]]::new()
        if (Test-Path -Path $script:DocsPath) {
            $DocFileParams = @{
                Path    = $script:DocsPath
                Filter  = '*.md'
                Recurse = $true
                File    = $true
            }
            Get-ChildItem @DocFileParams | ForEach-Object {
                $Relative = $_.FullName.Substring($script:DocsPath.Length)
                $Relative = $Relative.TrimStart('\', '/') -replace '\\', '/'
                $script:DocFiles.Add($Relative)
            }
        }

        $Ordinal = [System.StringComparer]::Ordinal
        $script:DocFileSet = [System.Collections.Generic.HashSet[string]]::new(
            [string[]]$script:DocFiles, $Ordinal)
        $script:NavPathSet = [System.Collections.Generic.HashSet[string]]::new(
            [string[]]$script:NavPaths, $Ordinal)
    }

    It 'has a docs_dir folder' {
        $script:DocsPath | Should -Exist
    }

    It 'has a nav section with at least one page' {
        $script:NavPaths.Count | Should -BeGreaterThan 0
    }

    It 'points every nav entry at an existing file' {
        $Missing = @($script:NavPaths | Where-Object {
                -not $script:DocFileSet.Contains($_)
            })
        $Because = "every nav path should exist under $($script:DocsDir)/" +
        " (case-sensitive), found none named: $($Missing -join ', ')"
        $Missing | Should -BeNullOrEmpty -Because $Because
    }

    It 'lists every markdown file in the nav' {
        $Orphaned = @($script:DocFiles | Where-Object {
                -not $script:NavPathSet.Contains($_)
            })
        $Because = 'every markdown page should be reachable from the nav,' +
        " not listed: $($Orphaned -join ', ')"
        $Orphaned | Should -BeNullOrEmpty -Because $Because
    }
}
